apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ayushbhagat/hello-world-app
    newTag: v1   # Start with v1; Image Updater will change this to v2, v3 etc.

