apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
spec:
  type: NodePort   # NodePort if using local cluster
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
