name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️ Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3️ Build Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=ayushbhagat/hello-world-app
          IMAGE_TAG=${GITHUB_SHA::7}  # short commit hash
          echo "Building image $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

      # 4️ Push Docker image
      - name: Push Docker Image
        run: |
          IMAGE_NAME=ayushbhagat/hello-world-app
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "Pushing image $IMAGE_NAME:$IMAGE_TAG and latest"
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
