name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "app/**"                 # Trigger if app code changes
      - "Dockerfile"             # Trigger if Dockerfile changes
      - ".github/workflows/**"   # Trigger if workflow config changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ayushbhagat/hello-world-app
          IMAGE_TAG=v${GITHUB_RUN_NUMBER}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=ayushbhagat/hello-world-app
          IMAGE_TAG=v${GITHUB_RUN_NUMBER}
          docker push $IMAGE_NAME:$IMAGE_TAG
          
